// Purpose: Starts the program, reads the input Sample Program, calls the lexical analyzer and parser, displays the tokens, and prints the final syntax result.
// Contains the main function of the LearnCompiler program.
// Handles program execution, reads the sample program, displays the generated tokens, and starts the syntax analysis.
#include <iostream>
#include <fstream>
#include <vector>

#include "token.h"
#include "lexer.h"
#include "parser.h"

int main()
{
    std::string filename;

    std::cout << "Enter input file name: ";
    std::cin >> filename;

    // Open the input file
    std::ifstream inputFile(filename);

    if (!inputFile)
    {
        std::cout << "Error: Could not open input file."
                  << std::endl;

        return 1;
    }

    // Create the lexer
    Lexer lexer(inputFile);

    // Generate tokens
    std::vector<Token> tokens = lexer.tokenize();

    // Display tokens
    std::cout << std::endl;
    std::cout << "LEXICAL ANALYZER OUTPUT" << std::endl;
    std::cout << "----------------------------------------"
              << std::endl;

    for (int i = 0; i < tokens.size(); i++)
    {
        std::cout << "Lexeme: "
                  << tokens[i].lexeme
                  << " | Token: "
                  << tokenTypeToString(tokens[i].type)
                  << " | Line: "
                  << tokens[i].lineNumber
                  << std::endl;
    }

    // Create the parser
    Parser parser(tokens);

    std::cout << std::endl;
    std::cout << "PARSER OUTPUT" << std::endl;
    std::cout << "----------------------------------------"
              << std::endl;

    // Parse the program
    if (parser.parseProgram())
    {
        std::cout
            << "The Sample Program is generated by the BNF grammar"
            << std::endl;
    }
    else
    {
        std::cout
            << "The Sample Program cannot be generated by the LearnCompiler BNF Grammar"
            << std::endl;
    }

    return 0;
}